# Packaging

set(CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP TRUE)
include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_NAME "Package Name")
set(CPACK_PACKAGE_VENDOR "Vendor Name")
set(CPACK_PACKAGE_VERSION "${GIT_TAG}")
set(CPACK_PACKAGE_FILE_NAME "Package-FileName-${GIT_TAG}-Installer")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Graphical User Interface for ${CPACK_PACKAGE_NAME}")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE.txt")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "${CPACK_PACKAGE_NAME}")

set(CPACK_COMPONENTS_ALL USER_INTERFACE)
set(CPACK_COMPONENT_USER_INTERFACE_DISPLAY_NAME "${CPACK_PACKAGE_NAME} User Interface")

# Append "Debug" to file name if build in debug mode
if (CMAKE_BUILD_TYPE MATCHES Debug)
    set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_FILE_NAME}-${CMAKE_BUILD_TYPE}")
endif()

# Qt Installer Framework generator
set(CPACK_IFW_VERBOSE ON)
set(CPACK_IFW_PRODUCT_URL "product_url.com")
set(CPACK_IFW_PACKAGE_ICON "${PROJECT_SOURCE_DIR}/rc/images/icon_file.ico")
set(CPACK_IFW_PACKAGE_LOGO "${PROJECT_SOURCE_DIR}/rc/images/logo.png")
set(CPACK_IFW_PACKAGE_WIZARD_STYLE "Classic")
set(CPACK_IFW_PACKAGE_WIZARD_SHOW_PAGE_LIST OFF)
set(CPACK_IFW_PACKAGE_NAME "${CPACK_PACKAGE_NAME}")
set(CPACK_IFW_PACKAGE_TITLE "${CPACK_PACKAGE_NAME}")
set(CPACK_IFW_ARCHIVE_FORMAT "zip")
set(CPACK_IFW_ARCHIVE_COMPRESSION 7)
set(CPACK_IFW_PACKAGE_CONTROL_SCRIPT "${CMAKE_SOURCE_DIR}/cmake/qtifw_control.qs")
set(CPACK_IFW_TARGET_DIRECTORY "@ApplicationsDirX64@/${CPACK_PACKAGE_INSTALL_DIRECTORY}")

# Finalize package

include(CPack)
include(CPackIFW REQUIRED)

cpack_ifw_configure_component(USER_INTERFACE
    FORCED_INSTALLATION
    NAME "${CPACK_COMPONENT_USER_INTERFACE_DISPLAY_NAME}"
    DISPLAY_NAME "${CPACK_COMPONENT_USER_INTERFACE_DISPLAY_NAME}"
    VERSION "${GIT_TAG}"
    SCRIPT "${CMAKE_SOURCE_DIR}/cmake/qtifw_component.qs"
    LICENSES "License" "${CPACK_RESOURCE_FILE_LICENSE}"
    DEFAULT "true"
)
